# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "omelet-ui"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jonathan Martin, Wylie McEvoy, Brian Aikens, Jarad Mallard, Ky Lee"]
  s.date = "2012-09-17"
  s.description = "Adds a mountable interface and API for adding/requesting/querying reports on a local Omelet report queue server."
  s.email = "me@nybblr.com"
  s.extra_rdoc_files = [
    "README.md",
    "README.rdoc"
  ]
  s.files = [
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/assets/images/rails.png",
    "app/assets/javascripts/application.js",
    "app/assets/javascripts/reports.js.coffee",
    "app/assets/stylesheets/application.css",
    "app/assets/stylesheets/reports.css.scss",
    "app/controllers/application_controller.rb",
    "app/controllers/reports_controller.rb",
    "app/helpers/application_helper.rb",
    "app/helpers/reports_helper.rb",
    "app/mailers/.gitkeep",
    "app/models/.gitkeep",
    "app/models/template.rb",
    "app/views/layouts/application.html.haml",
    "app/views/reports/edit.html.haml",
    "app/views/reports/index.html.haml",
    "app/views/reports/show.html.haml",
    "config.ru",
    "config/application.rb",
    "config/boot.rb",
    "config/database.yml",
    "config/environment.rb",
    "config/environments/development.rb",
    "config/environments/production.rb",
    "config/environments/test.rb",
    "config/initializers/backtrace_silencers.rb",
    "config/initializers/inflections.rb",
    "config/initializers/kaminari_config.rb",
    "config/initializers/mime_types.rb",
    "config/initializers/secret_token.rb",
    "config/initializers/session_store.rb",
    "config/initializers/simple_form.rb",
    "config/initializers/wrap_parameters.rb",
    "config/locales/en.yml",
    "config/locales/simple_form.en.yml",
    "config/routes.rb",
    "db/migrate/20120914192350_create_templates.rb",
    "db/seeds.rb",
    "doc/README_FOR_APP",
    "lib/assets/.gitkeep",
    "lib/omelet-ui/engine.rb",
    "lib/tasks/.gitkeep",
    "lib/templates/haml/scaffold/_form.html.haml",
    "log/.gitkeep",
    "omelet-ui.gemspec",
    "public/404.html",
    "public/422.html",
    "public/500.html",
    "public/favicon.ico",
    "public/index.html",
    "public/robots.txt",
    "script/rails",
    "spec/controllers/reports_controller_spec.rb",
    "spec/helpers/reports_helper_spec.rb",
    "spec/models/template_spec.rb",
    "spec/spec_helper.rb",
    "spec/views/reports/edit.html.haml_spec.rb",
    "spec/views/reports/index.html.haml_spec.rb",
    "spec/views/reports/show.html.haml_spec.rb",
    "vendor/assets/javascripts/.gitkeep",
    "vendor/assets/stylesheets/.gitkeep",
    "vendor/plugins/.gitkeep"
  ]
  s.homepage = "http://github.com/nybblr/omelet-ui"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Front-end Rails engine for Omelet report queue."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["= 3.2.8"])
      s.add_runtime_dependency(%q<sqlite3>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<paperclip>, [">= 0"])
      s.add_runtime_dependency(%q<friendly_id>, [">= 0"])
      s.add_runtime_dependency(%q<stipulate>, [">= 0"])
      s.add_runtime_dependency(%q<simple_form>, [">= 0"])
      s.add_runtime_dependency(%q<kaminari>, [">= 0"])
      s.add_runtime_dependency(%q<bourbon>, [">= 0"])
      s.add_runtime_dependency(%q<foreman>, [">= 0"])
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_runtime_dependency(%q<rabl>, [">= 0"])
      s.add_runtime_dependency(%q<squeel>, [">= 0"])
      s.add_runtime_dependency(%q<rb-readline>, [">= 0"])
      s.add_runtime_dependency(%q<jquery-rails>, [">= 0"])
      s.add_development_dependency(%q<haml-rails>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["= 3.2.8"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<paperclip>, [">= 0"])
      s.add_dependency(%q<friendly_id>, [">= 0"])
      s.add_dependency(%q<stipulate>, [">= 0"])
      s.add_dependency(%q<simple_form>, [">= 0"])
      s.add_dependency(%q<kaminari>, [">= 0"])
      s.add_dependency(%q<bourbon>, [">= 0"])
      s.add_dependency(%q<foreman>, [">= 0"])
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<rabl>, [">= 0"])
      s.add_dependency(%q<squeel>, [">= 0"])
      s.add_dependency(%q<rb-readline>, [">= 0"])
      s.add_dependency(%q<jquery-rails>, [">= 0"])
      s.add_dependency(%q<haml-rails>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.2.8"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<paperclip>, [">= 0"])
    s.add_dependency(%q<friendly_id>, [">= 0"])
    s.add_dependency(%q<stipulate>, [">= 0"])
    s.add_dependency(%q<simple_form>, [">= 0"])
    s.add_dependency(%q<kaminari>, [">= 0"])
    s.add_dependency(%q<bourbon>, [">= 0"])
    s.add_dependency(%q<foreman>, [">= 0"])
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<rabl>, [">= 0"])
    s.add_dependency(%q<squeel>, [">= 0"])
    s.add_dependency(%q<rb-readline>, [">= 0"])
    s.add_dependency(%q<jquery-rails>, [">= 0"])
    s.add_dependency(%q<haml-rails>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
  end
end

